NAME: DiffusionUNet
PRETRAINED_PATH:
IN_CHANNELS: 16
OUT_CHANNELS: 8
MODEL_CHANNELS: 256
NUM_HEADS: 8
NUM_RES_BLOCKS: 2
ATTENTION_RESOLUTIONS: [4,]
CHANNEL_MULT: [ 1, 2, 4, 4 ]
CONV_RESAMPLE: True
DIMS: 2
USE_CHECKPOINT: False
USE_SCALE_SHIFT_NORM: False
RESBLOCK_UPDOWN: False
USE_SPATIAL_TRANSFORMER: True
TRANSFORMER_DEPTH: 1
DISABLE_MIDDLE_SELF_ATTN: False
USE_LINEAR_IN_TRANSFORMER: False

diffusion:
    beta_schedule: linear
    beta_start: 0.00085
    beta_end: 0.0120
    num_diffusion_timesteps: 1000

